### ISSUE TITLE
gzip: stdout: Broken pipe

### ISSUE THREAD

**Issue by BirongZhang** [Nusob888/fasterqParseR#8] opened 2023-10-17 14:45 UTC
Hey Bo,

I hope you are well.

I have problems again. Could you please help me have a look at?

Here is my code:
```
library(fasterqParseR)
working_directory = "/scratch/c.c2050857/GSE216836/"
input_directory = "/scratch/c.c2050857/GSE216836/raw_data/"
output_directory = "/scratch/c.c2050857/GSE216836/split_data/"

assigned_files <- assignSRAreads(working_dir = working_directory, input_dir = input_directory, outdir = output_directory, parallel=TRUE)
renameAll(assigned_SRA= assigned_files, input_dir=input_directory, format="cellranger")

```

Here is my file:
<img width="270" alt="Screenshot 2023-10-17 at 15 41 01" src="https://github.com/Nusob888/fasterqParseR/assets/74430395/35d2f872-fdc5-4fd3-a81c-ca23ddd552ec">

And error:
```
[1] "First n=250 read lengths will be output into outdir"
gzip: stdout: Broken pipe
gzip: stdout: Broken pipe
```

I can get those .txt output and a messy assigned_SRAreads.csv(all SSR ID came in one row), but no .fastq output.
Any advice would be highly appreciated! Many thanks!

Kind regards,
Birong

**Comment by Nusob888** [comment] 2024-02-22 23:55
Hi Sorry for the long delay. A student of mine has looked into this. I think the issue is with the zcat | awk command as it examines every other line so likely finishes before gzip finishes compression. It should not affect the output. 

The messy csv has been fixed, I am just waiting for a pull request once my student has time and it should be fixed. Thank you for your patience and continued use of the package

**Comment by sxf-ux** [comment] 2024-03-07 15:26
> Hey Bo,
> 
> I hope you are well.
> 
> I have problems again. Could you please help me have a look at?
> 
> Here is my code:
> 
> ```
> library(fasterqParseR)
> working_directory = "/scratch/c.c2050857/GSE216836/"
> input_directory = "/scratch/c.c2050857/GSE216836/raw_data/"
> output_directory = "/scratch/c.c2050857/GSE216836/split_data/"
> 
> assigned_files <- assignSRAreads(working_dir = working_directory, input_dir = input_directory, outdir = output_directory, parallel=TRUE)
> renameAll(assigned_SRA= assigned_files, input_dir=input_directory, format="cellranger")
> ```
> 
> Here is my file: <img alt="Screenshot 2023-10-17 at 15 41 01" width="270" src="https://private-user-images.githubusercontent.com/74430395/275872749-35d2f872-fdc5-4fd3-a81c-ca23ddd552ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MjUxMjAsIm5iZiI6MTcwOTgyNDgyMCwicGF0aCI6Ii83NDQzMDM5NS8yNzU4NzI3NDktMzVkMmY4NzItZmRjNS00ZmQzLWE4MWMtY2EyM2RkZDU1MmVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDE1MjAyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5NWNmZGE4NDVjNGJiNmJlOTU0ZDc2Zjk2YmY4M2FlNjQ0MmEwOWVhMGRlNjdmYjIwYmRiNTFlMjFhZmE3YjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.q6yNsGaPh0YqpF0e5kYS873wtX1-WMkAfJJvFYkfoeQ">
> 
> And error:
> 
> ```
> [1] "First n=250 read lengths will be output into outdir"
> gzip: stdout: Broken pipe
> gzip: stdout: Broken pipe
> ```
> 
> I can get those .txt output and a messy assigned_SRAreads.csv(all SSR ID came in one row), but no .fastq output. Any advice would be highly appreciated! Many thanks!
> 
> Kind regards, Birong

Hi Birong,

I can confirm that the `stdout: Broken pipe` is a message due to ` zcat /project/fastqfile/ | head -1000`. 

if 1000 lines have been read and funnelled into `| head` , it closes the zcat. However, this message doesnt impact anything downstream.

Also, the csv error has now been fixed so feel free to redownload the package again. Check the home page for a link to an example code to help run the package.

**Comment by Nusob888** [comment] 2024-03-28 14:37
@BirongZhang, I am closing this as we haven't heard anything, but please do make another issue if the code still doesn't work

**Closed as completed by Nusob888** 2024-03-28 14:37 UTC
